#ifdef DEVICE_UP1_GW_RS485

    #include "HardwareConfig/OpenKNX/UP1.h"
    #undef RS485_SERIAL
    #define RS485_SERIAL SerialPio
#endif

#ifdef DEVICE_REG1_GW_RS485

    #include "HardwareConfig/OpenKNX/REG1.h"
    #define OKNXHW_REG1_SENSOR_SDA_TX_PIN (8) // RP2040 GPIO 8 / SPI1 RX / UART1 TX / I2C0 SDA / PWM4 A
    #define OKNXHW_REG1_SENSOR_SCL_RX_PIN (9) // RP2040 GPIO 9 / SPI1 CSn / UART1 RX / I2C0 SCL / PWM4 B

    #define RS485_SERIAL SerialPio

    #define I2C_WIRE Wire
    #define I2C_SDA_PIN OKNXHW_REG1_SENSOR_SDA_TX_PIN
    #define I2C_SCL_PIN OKNXHW_REG1_SENSOR_SCL_RX_PIN

    #define OPENKNX_BI_GPIO_PINS OKNXHW_REG1_APP_GW_RS485_BINARY_INPUT1_PIN, OKNXHW_REG1_APP_GW_RS485_BINARY_INPUT2_PIN, OKNXHW_REG1_APP_GW_RS485_BINARY_INPUT3_PIN, OKNXHW_REG1_APP_GW_RS485_BINARY_INPUT4_PIN
    #define OPENKNX_BI_GPIO_COUNT 4
    #define OPENKNX_BI_ONLEVEL OKNXHW_REG1_APP_GW_RS485_BINARY_INPUT_ONLEVEL

#endif

#ifdef TESTDEVICE_PIPICO_GW_RS485

    // Debug PiPico

    #define PROG_LED_PIN (2)
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN (7)
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
    #define KNX_SERIAL Serial1
    #define KNX_UART_RX_PIN (1)
    #define KNX_UART_TX_PIN (0)

    #define RS485_SERIAL Serial2
    #define RS485_UART_RX_PIN (5)
    #define RS485_UART_TX_PIN (4)
    #define RS485_UART_DIR_PIN (3)


#endif

